---
query_categories:
  -
    category_key: category_generation
    criteria:
      -
        answer_keys: []
        criteria_key: criteria_generation_boomer
        name: "Baby Boomer (born 1946-1964)"
      -
        answer_keys: []
        criteria_key: criteria_generation_x
        name: "Gen X (born 1965-1980)"
      -
        answer_keys: []
        criteria_key: criteria_generation_millennial
        name: "Millennial (born 1981-1996)"
      -
        answer_keys: []
        criteria_key: criteria_generation_z
        name: "Gen Z (born 1995-2001)"
    group: Demographics
    name: Age
  -
    category_key: category_children
    criteria:
      -
        answer_keys:
          - answer_children_none
        criteria_key: criteria_children_none
        name: "No Children"
      -
        answer_keys:
          - answer_children_young
        criteria_key: criteria_children_young
        name: "Parents of Young Children"
      -
        answer_keys:
          - answer_children_teen
        criteria_key: criteria_children_teen
        name: "Parents of Teenagers"
      -
        answer_keys:
          - answer_children_adult
        criteria_key: criteria_children_adult
        name: "Parents of Adult Children"
    group: Demographics
    name: Children
  -
    category_key: category_country
    criteria:
      -
        answer_keys: []
        criteria_key: criteria_country_us
        name: "United States of America"
      -
        answer_keys: []
        criteria_key: criteria_country_ca
        name: Canada
      -
        answer_keys: []
        criteria_key: criteria_country_au
        name: Australia
      -
        answer_keys: []
        criteria_key: criteria_country_gb
        name: "United Kingdom"
    group: Demographics
    name: Country
  -
    category_key: category_dweller
    criteria:
      -
        answer_keys:
          - answer_dweller_metropolis
        criteria_key: criteria_dweller_metropolis
        name: "Metropolis Dweller"
      -
        answer_keys:
          - answer_dweller_urban
          - answer_dweller_metropolis
        criteria_key: criteria_dweller_urban
        name: "Urban Dweller"
      -
        answer_keys:
          - answer_dweller_suburban
        criteria_key: criteria_dweller_suburban
        name: "Suburban Dweller"
      -
        answer_keys:
          - answer_dweller_rural
        criteria_key: criteria_dweller_rural
        name: "Rural Dweller"
    group: Demographics
    name: "Urban/Rural Dwelling"
  -
    category_key: category_education
    criteria:
      -
        answer_keys:
          - answer_education_highschool
        criteria_key: criteria_education_highschool
        name: "High School"
      -
        answer_keys:
          - answer_education_vocational
        criteria_key: criteria_education_vocational
        name: "Vocational Training"
      -
        answer_keys:
          - answer_education_college
        criteria_key: criteria_education_college
        name: "College or Bachelor’s Degree"
      -
        answer_keys:
          - answer_education_postgraduate
          - answer_education_doctorate
        criteria_key: criteria_education_college
        name: "Postgraduate Degree"
    group: Demographics
    name: Education
  -
    category_key: category_employment
    criteria:
      -
        answer_keys:
          - answer_employment_fulltime
        criteria_key: criteria_employment_fulltime
        name: Full-time
      -
        answer_keys:
          - answer_employment_parttime
        criteria_key: criteria_employment_parttime
        name: Part-time
      -
        answer_keys:
          - answer_employment_seeking
        criteria_key: criteria_employment_seeking
        name: "Job Seeker"
      -
        answer_keys:
          - answer_employment_student
        criteria_key: criteria_employment_student
        name: Student
      -
        answer_keys:
          - answer_employment_retired
        criteria_key: criteria_employment_retired
        name: Retired
    group: Demographics
    name: "Employment Status"
  -
    category_key: category_gender
    criteria:
      -
        answer_keys:
          - answer_gender_female
        criteria_key: criteria_gender_female
        name: Female
      -
        answer_keys:
          - answer_gender_male
        criteria_key: criteria_gender_male
        name: Male
      -
        answer_keys:
          - answer_gender_female
          - answer_gender_male
          - answer_gender_nonbinary
          - answer_gender_noanswer
        criteria_key: criteria_gender_all
        name: All
    group: Demographics
    name: Gender
  -
    category_key: category_income
    criteria:
      -
        answer_keys:
          - answer_income_struggling
          - answer_income_monthtomonth
        criteria_key: criteria_income_low
        name: "Low Income"
      -
        answer_keys:
          - answer_income_monthtomonth
          - answer_income_middle
        criteria_key: criteria_income_medium
        name: "Medium Income"
      -
        answer_keys:
          - answer_income_comfortable
          - answer_income_verycomfortable
        criteria_key: criteria_income_aboveaverage
        name: "Above Average Income"
    group: Demographics
    name: "Financial Situation"
  -
    category_key: category_adopter
    criteria:
      -
        answer_keys:
          - answer_adopter_thefirst
          - answer_adopter_oneofthefirst
        criteria_key: criteria_adopter_earlyadopter
        name: "Early Adopter"
      -
        answer_keys:
          - answer_adopter_earlymajority
        criteria_key: criteria_adopter_earlymajority
        name: "Early Majority"
      -
        answer_keys:
          - answer_adopter_latemajority
          - answer_adopter_laggard
        criteria_key: criteria_adopter_latemajority
        name: "Late Majority"
      -
        answer_keys:
          - answer_adopter_laggard
        criteria_key: criteria_adopter_laggard
        name: Laggard
    group: Psychographics
    name: "Early/Late Adopter"
  -
    category_key: category_interest
    criteria:
      -
        answer_keys: []
        criteria_key: criteria_interest_apps
        name: Apps
      -
        answer_keys: []
        criteria_key: criteria_interest_athlete
        name: Athlete
      -
        answer_keys: []
        criteria_key: criteria_interest_carowner
        name: "Car Owner"
      -
        answer_keys: []
        criteria_key: criteria_interest_commuter
        name: Commuter
      -
        answer_keys: []
        criteria_key: criteria_interest_consciousconsumer
        name: "Conscious Consumer"
      -
        answer_keys: []
        criteria_key: criteria_interest_digitalnative
        name: "Digital Native"
      -
        answer_keys: []
        criteria_key: criteria_interest_entrepreneur
        name: Entrepreneur
      -
        answer_keys: []
        criteria_key: criteria_interest_fashion
        name: Fashion
      -
        answer_keys: []
        criteria_key: criteria_interest_fastfood
        name: "Fast Food"
      -
        answer_keys: []
        criteria_key: criteria_interest_fitness
        name: Fitness
      -
        answer_keys: []
        criteria_key: criteria_interest_foodie
        name: Foodie
      -
        answer_keys: []
        criteria_key: criteria_interest_frequentflyer
        name: "Frequent Flyer"
      -
        answer_keys: []
        criteria_key: criteria_interest_gadgets
        name: Gadgets
      -
        answer_keys: []
        criteria_key: criteria_interest_gamer
        name: Gamer
      -
        answer_keys: []
        criteria_key: criteria_interest_gardening
        name: Gardening
      -
        answer_keys: []
        criteria_key: criteria_interest_gigeconomy
        name: "Gig Economy"
      -
        answer_keys: []
        criteria_key: criteria_interest_healthconscious
        name: "Health Conscious"
      -
        answer_keys: []
        criteria_key: criteria_interest_healthworker
        name: "Health Worker"
      -
        answer_keys: []
        criteria_key: criteria_interest_homeimprovement
        name: "Home Improvement"
      -
        answer_keys: []
        criteria_key: criteria_interest_homeowner
        name: "Home Owner"
      -
        answer_keys: []
        criteria_key: criteria_interest_mindfulness
        name: Mindfulness/Yoga
      -
        answer_keys: []
        criteria_key: criteria_interest_outdoorsy
        name: Outdoorsy
      -
        answer_keys: []
        criteria_key: criteria_interest_petowner
        name: "Pet Owner"
      -
        answer_keys: []
        criteria_key: criteria_interest_quantifiedself
        name: "Quantified Self"
      -
        answer_keys: []
        criteria_key: criteria_interest_smallbusinessowner
        name: "Small Business Owner"
      -
        answer_keys: []
        criteria_key: criteria_interest_smarthome
        name: "Smart Home"
      -
        answer_keys: []
        criteria_key: criteria_interest_tradesperson
        name: Tradesman/woman
      -
        answer_keys: []
        criteria_key: criteria_interest_vegetarian
        name: Vegetarian
      -
        answer_keys: []
        criteria_key: criteria_interest_vegan
        name: Vegan
    group: Psychographics
    name: Interests
  -
    category_key: category_publication
    criteria:
      -
        answer_keys: []
        criteria_key: criteria_publication_architecturaldigest
        name: "Architectural Digest"
      -
        answer_keys: []
        criteria_key: criteria_publication_bloombergbusinessweek
        name: "Bloomberg Businessweek"
      -
        answer_keys: []
        criteria_key: criteria_publication_cosmopolitan
        name: Cosmopolitan
      -
        answer_keys: []
        criteria_key: criteria_publication_elle
        name: Elle
      -
        answer_keys: []
        criteria_key: criteria_publication_fastcompany
        name: "Fast Company"
      -
        answer_keys: []
        criteria_key: criteria_publication_foodnetworkmagazine
        name: "Food Network Magazine"
      -
        answer_keys: []
        criteria_key: criteria_publication_forbes
        name: Forbes
      -
        answer_keys: []
        criteria_key: criteria_publication_fortune
        name: Fortune
      -
        answer_keys: []
        criteria_key: criteria_publication_gq
        name: GQ
      -
        answer_keys: []
        criteria_key: criteria_publication_goodhousekeeping
        name: "Good Housekeeping"
      -
        answer_keys: []
        criteria_key: criteria_publication_instyle
        name: InStyle
      -
        answer_keys: []
        criteria_key: criteria_publication_marieclaire
        name: "Marie Claire"
      -
        answer_keys: []
        criteria_key: criteria_publication_menshealth
        name: "Men's Health"
      -
        answer_keys: []
        criteria_key: criteria_publication_nationalgeographic
        name: "National Geographic"
      -
        answer_keys: []
        criteria_key: criteria_publication_people
        name: People
      -
        answer_keys: []
        criteria_key: criteria_publication_popularmechanics
        name: "Popular Mechanics"
      -
        answer_keys: []
        criteria_key: criteria_publication_popularscience
        name: "Popular Science"
      -
        answer_keys: []
        criteria_key: criteria_publication_rollingstone
        name: "Rolling Stone"
      -
        answer_keys: []
        criteria_key: criteria_publication_sportsillustrated
        name: "Sports Illustrated"
      -
        answer_keys: []
        criteria_key: criteria_publication_thenewyorker
        name: "The New Yorker"
      -
        answer_keys: []
        criteria_key: criteria_publication_timeout
        name: "Time Out"
      -
        answer_keys: []
        criteria_key: criteria_publication_time
        name: Time
      -
        answer_keys: []
        criteria_key: criteria_publication_usweekly
        name: "Us Weekly"
      -
        answer_keys: []
        criteria_key: criteria_publication_vanityfair
        name: "Vanity Fair"
      -
        answer_keys: []
        criteria_key: criteria_publication_wired
        name: Wired
      -
        answer_keys: []
        criteria_key: criteria_publication_womenshealth
        name: "Women's Health"
    group: Psychographics
    name: Publications
survey_questions:
  -
    answers:
      -
        answer_key: answer_education_highschool
        text: "High school diploma"
      -
        answer_key: answer_education_vocational
        text: "Vocational training"
      -
        answer_key: answer_education_college
        text: "College or bachelor’s degree"
      -
        answer_key: answer_education_postgraduate
        text: "Postgraduate or master’s degree"
      -
        answer_key: answer_education_doctorate
        text: "Doctorate degree"
      -
        answer_key: answer_education_other
        text: Other
      -
        answer_key: answer_education_none
        text: "None of these"
    question_key: question_education
    text: "What’s the highest level of education you have completed?"
    type: single
  -
    answers:
      -
        answer_key: answer_gender_female
        text: Female
      -
        answer_key: answer_gender_male
        text: Male
      -
        answer_key: answer_gender_nonbinary
        text: "Non-binary or other"
      -
        answer_key: answer_gender_noanswer
        text: "Prefer not to say"
    question_key: question_gender
    text: "What is your gender?"
    type: single
  -
    answers:
      -
        answer_key: answer_income_struggling
        text: "Sometimes paying the monthly bills is a struggle"
      -
        answer_key: answer_income_monthtomonth
        text: "Living month to month and just breaking even"
      -
        answer_key: answer_income_middle
        text: "Have enough but should save more"
      -
        answer_key: answer_income_comfortable
        text: "Living comfortably, with some money left over at the end of each month"
      -
        answer_key: answer_income_verycomfortable
        text: "Living very comfortably, and spending freely on things I enjoy"
    question_key: question_income
    text: "Which of the following best describes where you stand financially?"
    type: single
  -
    answers:
      -
        answer_key: answer_adopter_thefirst
        text: "I’m always the first of my friends to try new products and services. I’ll camp out in line over night if it means being first!"
      -
        answer_key: answer_adopter_oneofthefirst
        text: "I’m usually one of the first to try a new product or service, but I’ll wait for the long line to die down."
      -
        answer_key: answer_adopter_earlymajority
        text: "I’m happy to try new products or services if sources I respect vouch for them"
      -
        answer_key: answer_adopter_latemajority
        text: "If over time I continually hear great things about a product or service, I’d be willing to try it out."
      -
        answer_key: answer_adopter_laggard
        text: "I prefer to stick with my tried and trusted brands and products"
    question_key: question_adopter
    text: "Which of these statements best describes you?"
    type: single
  -
    answers:
      -
        answer_key: answer_dweller_metropolis
        text: "Metropolis: my city never sleeps"
      -
        answer_key: answer_dweller_city
        text: "City: it’s all about the hustle and bustle"
      -
        answer_key: answer_dweller_suburban
        text: "Suburban area: it’s peaceful, but within easy reach of a city"
      -
        answer_key: answer_dweller_rural
        text: "Rural area: there’s nature all around and going to the city is a trip"
    question_key: question_dweller
    text: "Which of these best describes where you live?"
    type: single
  -
    answers:
      -
        answer_key: answer_children_none
        text: "No"
      -
        answer_key: answer_children_young
        text: "Yes, I have one or more kids younger than 12"
      -
        answer_key: answer_children_teen
        text: "Yes, I have one or more kids aged 12-17"
      -
        answer_key: answer_children_adult
        text: "Yes, but my kids are older than 17"
    question_key: question_children
    text: "Do you have any children?"
    type: multiple
  -
    answers:
      -
        answer_key: answer_employment_fulltime
        text: "I have a full time job (35+ hours per week)"
      -
        answer_key: answer_employment_parttime
        text: "I work part time"
      -
        answer_key: answer_employment_seeking
        text: "I’m currently looking for a job"
      -
        answer_key: answer_employment_student
        text: "I’m a student (full or part time)"
      -
        answer_key: answer_employment_retired
        text: "I’m retired"
      -
        answer_key: answer_employment_other
        text: Other
    question_key: question_employment
    text: "Which best describes your work situation?"
    type: multiple
